/* eslint-disable id-length */
module.exports = {
  KingSenteA: require("./0GY"),
  KingGoteB: require("./1GY"),
  RookA: require("./0HI"),
  RookB: require("./1HI"),
  DragonKingA: require("./0RY"),
  DragonKingB: require("./1RY"),
  BishopA: require("./0KA"),
  BishopB: require("./1KA"),
  DragonHorseA: require("./0UM"),
  DragonHorseB: require("./1UM"),
  GoldGeneralA: require("./0KI"),
  GoldGeneralB: require("./1KI"),
  SilverGeneralA: require("./0GI"),
  SilverGeneralB: require("./1GI"),
  PromotedSilverGeneralA: require("./0NG"),
  PromotedSilverGeneralB: require("./1NG"),
  KnightA: require("./0KE"),
  KnightB: require("./1KE"),
  PromotedKnightA: require("./0NK"),
  PromotedKnightB: require("./1NK"),
  LanceA: require("./0KY"),
  LanceB: require("./1KY"),
  PromotedLanceA: require("./0NY"),
  PromotedLanceB: require("./1NY"),
  PawnA: require("./0FU"),
  PawnB: require("./1FU"),
  PromotedPawnA: require("./0TO"),
  PromotedPawnB: require("./1TO"),
  Empty: require("./Empty")
};
